name: CI

on: [push]

jobs:
  test-old-ufl:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dev-env:current-mpich
    env:
      CC: cc
      CXX: c++
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
      HDF5_MPI: "ON"
      HDF5_DIR: "/usr/local/"
      PYTHONPATH: "/usr/local/dolfinx-linux-gnu-real64-32/lib/python3.12/dist-packages:/usr/local/lib"
      LD_LIBRARY_PATH: "/usr/local/petsc/linux-gnu-real64-32/lib/:/usr/local"
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
    steps: 
      - uses: actions/checkout@v4

      - name: Install DOLFINx
        uses: jorgensd/actions/install-dolfinx@v0.4
        with:
          ufl: be83aefdc4fceaab5458025703ff8fbb029e0c5a

      - name: Install dolfiny
        run: pip install .[all]
      
      - name: Run plasticity
        working-directory: demo/plasticity
        run: python solid_plasticity_monolithic.py

  test-new-ufl:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dev-env:current-mpich
    env:
      CC: cc
      CXX: c++
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
      HDF5_MPI: "ON"
      HDF5_DIR: "/usr/local/"
      PYTHONPATH: "/usr/local/dolfinx-linux-gnu-real64-32/lib/python3.12/dist-packages:/usr/local/lib"
      LD_LIBRARY_PATH: "/usr/local/petsc/linux-gnu-real64-32/lib/:/usr/local"
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
    steps: 
      - uses: actions/checkout@v4

      - name: Install DOLFINx
        uses: jorgensd/actions/install-dolfinx@v0.4
        with:
          ufl-repository: firedrakeproject/ufl
          ufl: pbrubeck/fix/indexed-conditional
      
      - name: Install dolfiny
        run: pip install .[all]
      
      - name: Run plasticity
        working-directory: demo/plasticity
        run: python solid_plasticity_monolithic.py

